### ISSUE TITLE
Please link to this repo on About page

### ISSUE THREAD

**Issue by answerquest** [osm-in/osm-tasking-manager2#11]
http://tasks.openstreetmap.in/about

There's no link to here, that's why started emailing about the recent blockage at different places. Sorry about that!

**Comment by geohacker** [comment]
@answerquest - we're likely not going to change the about page. Always note to open a ticket here and tag me and @batpad. Thanks!

**Comment by answerquest** [comment]
ok. I'll leave it to the developers to share this instruction with all the other people who have or will set up tasks on this site, because there's no way I can do that, and the only way they'll ever read this instruction is if someone gives them the link to this repo to begin with and if they bother to rummage about the closed issues.
