### ISSUE TITLE
Next release

### ISSUE THREAD

**Issue by geohacker** [osm-in/osm-tasking-manager2#5]
@batpad - just outlining things to move before next release on tasks.openstreetmap.in:
- [ ] invalidate tasks #1 
- [ ] fix translation https://github.com/hotosm/osm-tasking-manager2#initializing-translation-files
- [ ] update default hashtag to #osm-india

@mikelmaron @planemad @arunasank

**Comment by mikelmaron** [comment]
@geohacker is default hashtag a configuration variable?

**Comment by batpad** [comment]
Looks like it is hard-coded here: https://github.com/osm-in/osm-tasking-manager2/blob/master/osmtm/models.py#L620

@geohacker guess we should have a separate issue to make that a config variable.

/cc @mikelmaron

**Comment by batpad** [comment]
@geohacker do you think we can setup a time to do this next week? I think both my Pull Requests should definitely be merged upstream - I feel we can go ahead and merge into our fork and deploy.

**Comment by batpad** [comment]
All this has been done. Closing.
