### ISSUE TITLE
JOSM RC does not work from the tasking manager when using custom imagery.

### ISSUE THREAD

**Issue by maning** [osm-in/osm-tasking-manager2#7]
When adding a custom imagery source in tasks.openstreetmap.id, we cannot download task using `Edit with JOSM`.
![screen shot 2015-10-15 at 3 08 34 pm](https://cloud.githubusercontent.com/assets/353700/10511102/a3ce0f70-7354-11e5-9d5b-07106d5b6bc6.png)

**Comment by batpad** [comment]
@maning could you please check if this issue can be reproduced on the main Tasking Manager instance and then file an issue there? Thanks.

**Comment by maning** [comment]
@batpad, I've checked it on tasks.dev.hotosm.org and a private osm-ph instance and it works as expected.

**Comment by batpad** [comment]
oops, so this issue is specific to the india instance? sorry, @maning re-opening.

/cc @geohacker any idea why this might be going on? @maning do you know if this issue has cropped up recently or has existing before?

**Comment by geohacker** [comment]
This is weird to me. Might take some digging.

**Comment by batpad** [comment]
@maning sorry - can you confirm if this issue still persists or if it was something transient with JOSM or so? If it still exists, can you ping me so I can see what's going on? Thanks.

**Comment by batpad** [comment]
@maning sorry - just checking in here - is this still an issue? If not, please close. Thanks.

**Comment by maning** [comment]
Thought I closed this already.  Fell off the crack. Closing
