### ISSUE TITLE
Unread messages notification

### ISSUE THREAD

**Issue by ramyaragupathy** [osm-in/osm-tasking-manager2#8]
It'd be great if the unread messages popup doesn't keep flickering everytime we move to a new page.
Just one flicker when the user logins to task manager, is sufficient to grab attention.
![hot](https://cloud.githubusercontent.com/assets/12103383/15848660/e679c632-2cab-11e6-9dca-07e311981bf7.gif)

cc @batpad

**Comment by batpad** [comment]
@ramyaragupathy if this issue still exists, also on the main Tasking Manager, can you please file an issue upstream - https://github.com/hotosm/osm-tasking-manager2/ - closing here. thanks.
